### ISSUE TITLE
uu: Overflødig aria-haspopup på menyknappen

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/verktoykassen#25]
Fjern aria-haspopup="menu" fra menyknappen.  Den gir implikasjonen at headeren har en [meny-widget interaksjonsmønster](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html) (at man tabber til den, bruker pil inn i den, og tabber ut).  Det er tilstrekkelig med bare aria-expanded i dette tilfellet.

![image](https://user-images.githubusercontent.com/91880567/140373960-b6fc0249-0ee3-4d25-90cc-dd88e0639d60.png)

**Comment by KenAJoh** [comment]
TODO: fikset Dropdown.Toggle komponent med mulighet til å overskrive aria-haspopup

**Comment by sarahbrodwall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ny nettside: Luke ut UU-feil og mangler](https://trello.com/c/i3P6bWn6/46-ny-nettside-luke-ut-uu-feil-og-mangler)
