### ISSUE TITLE
uu: IDer kan ikke starte med tall

### ISSUE THREAD

**Issue by sarahbrodwall** [navikt/verktoykassen#28]
![image](https://user-images.githubusercontent.com/91880567/140380964-b8a95ee7-ee0c-4ae9-8539-f177d4ebe469.png)

IDer som starter med tall er ikke valid HTML.

**Comment by sarahbrodwall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ny nettside: Luke ut UU-feil og mangler](https://trello.com/c/i3P6bWn6/46-ny-nettside-luke-ut-uu-feil-og-mangler)

**Comment by KenAJoh** [comment]
TODO: Gå over alle komponenter i DS og prefikse ID
