### ISSUE TITLE
Browser tilbake og fram er litt buggy

### ISSUE THREAD

**Issue by andnorda** [navikt/verktoykassen#41]
Når jeg navigerer til https://design.nav.no/designsystem/side/komigang og så klikker på Flater i menyen, og så trykker tilbake i nettleseren så viser urlen komigang, men siden som vises er flater.

**Comment by KenAJoh** [comment]
Fikset ved å fjerne bruk av `next/link` i applikasjonen https://nextjs.org/docs/api-reference/next/link
Problemet virker som det er relatert til dynamiske sider, da de som ligger under `designsystem/[...slug].tsx`. Når man trykker back/forward i browser blur bare getStaticProps kjørt av og til, noe som gjør at innholdet for ny side ikke blir lastet inn. Jeg har ikke klart å finne ut hvorfor dette skjer. Er kjedelig å miste funksjonaliteten til `next/link`, men til denne buggen er fikset vil siden ikke kunne bruke det. 

Prøvde fikser:
- Fjerne react-modal. Noen fikk denne buggen når react.createPortal ble bruk.
- Force alle lenker til å ikke være `shallow`. Dette hjalp ikke da lenkene aldri var shallow..
- Force refresh ved history.pop. Fungerte ikke da effects ikke ble kjørt i det hele tatt ved back/forward noen ganger.

**Comment by KenAJoh** [comment]
Fikset: https://github.com/vercel/next.js/issues/33233
