### ISSUE TITLE
Kan vi visualisere diff-er i Sanity studio? 🙏 

### ISSUE THREAD

**Issue by finiteattention** [navikt/verktoykassen#44]
Bra at vi har versjonering, men jeg savner fortsatt en "synlig diff"-funksjon når jeg sitter og redigerer i Sanity studio. Jeg ønsker å kunne se på den nyeste versjon og forstå hvilke ting som kan være endret siden sist, gjerne av hvem, og når endringen ble gjort. (Dvs at dette er et annet behov enn det å kunne bla gjennom tidligere versjoner, én og én.)

Sanity sine docs har dette, som jeg ikke umiddelbart kan se at vi har implementert:
https://www.sanity.io/docs/custom-diff-components

Ville det vært mulig å få opp noe slik dersom den ikke allerede finnes? Takker :)

**Comment by KenAJoh** [comment]
Hei, dette skal være mulig allerede hvis jeg ikke har misforstått: 👇 


https://user-images.githubusercontent.com/26967723/147104629-ddfd56c3-4f0f-44ba-a1c5-6746ff1e03d5.mp4
